spring.application.name=MPF-Library-Spring-Boot
server.port=8080
app.custom.message=Welcome to our library!

spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.web.encoding.enabled=true
spring.web.encoding.force=true
spring.web.encoding.charset=UTF-8

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.servlet.content-type=text/html

spring.datasource.url=jdbc:h2:file:./data/guest;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# --- \u041D\u0430\u043B\u0430\u0448\u0442\u0443\u0432\u0430\u043D\u043D\u044F Gmail SMTP ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vynychenkoos@gmail.com
spring.mail.password=qdrt gpzy tuzk uxoq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# --- \u041D\u0430\u043B\u0430\u0448\u0442\u0443\u0432\u0430\u043D\u043D\u044F FreeMarker \u0434\u043B\u044F \u043F\u043E\u0448\u0442\u0438 ---
spring.freemarker.template-loader-path=classpath:/mail-templates/
spring.freemarker.charset=UTF-8

# --- \u0414\u043E\u0434\u0430\u0442\u043A\u043E\u0432\u0438\u0439 \u043F\u0430\u0440\u0430\u043C\u0435\u0442\u0440 \u0434\u043B\u044F \u0432\u0430\u0448\u043E\u0433\u043E MailService ---
app.mail.admin=vynychenkoos@gmail.com