spring.application.name=MPF-Library-Spring-Boot
server.port=8080
app.custom.message=Welcome to our library!

# --- \u041D\u0430\u043B\u0430\u0448\u0442\u0443\u0432\u0430\u043D\u043D\u044F JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- \u041D\u0430\u043B\u0430\u0448\u0442\u0443\u0432\u0430\u043D\u043D\u044F Flyway ---
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# --- \u0411\u0430\u0437\u0430 \u0434\u0430\u043D\u0438\u0445 ---
spring.datasource.url=jdbc:h2:file:./data/guest;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# --- \u041F\u043E\u0448\u0442\u0430 \u0442\u0430 \u0428\u0430\u0431\u043B\u043E\u043D\u0456\u0437\u0430\u0442\u043E\u0440\u0438 ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vynychenkoos@gmail.com
spring.mail.password=qdrt gpzy tuzk uxoq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.freemarker.template-loader-path=classpath:/mail-templates/
app.mail.admin=vynychenkoos@gmail.com